spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: 123four
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

jwt:
  secret: retroride-super-secret-key-must-be-at-least-256-bits!!
  expiration: 604800000


upload:
  dir: uploads



